Master Thesis: Analyse reddit entries with the big five personality model
dataset pandora reduced to only show the users with big five entries

Cells:
1. Import packages
2. Import data
3. Produce a smaller dataset as test material to not overstrain computer

Imports:
- jupyter notebook
- pandas

In [15]:
import pandas as pd
import random
random.seed(32)

In [4]:
data = pd.read_csv("/Users/sophiasylvester/ma_py/pandora_bigfive.csv")
data.head()

,author,author_flair_text,body,downs,created_utc,subreddit_id,link_id,parent_id,score,controversiality,gilded,id,subreddit,ups,word_count,word_count_quoteless,lang
0,-Areopagan-,NaN,Your first and second question is the same que...,NaN,1513882848,t5_32jqy,t3_72l671,t1_drizkiv,1.0,0,0,drkz7z6,JordanPeterson,NaN,201,201,en
1,-Areopagan-,NaN,"I have two friends. I alienate everyone, event...",NaN,1513744846,t5_32jqy,t3_72l671,t1_drhpj7t,1.0,0,0,dri9x7l,JordanPeterson,NaN,123,123,en
2,-Areopagan-,NaN,I suggest the future. You aren't going back in...,NaN,1522253427,t5_32jqy,t3_80q8vm,t1_dwf58q7,5.0,0,0,dwfb6pa,JordanPeterson,NaN,123,123,en
3,-Areopagan-,NaN,I am smarter than you and will work you into d...,NaN,1513704382,t5_32jqy,t3_72l671,t3_72l671,2.0,0,0,drh9s6q,JordanPeterson,NaN,70,55,en
4,-Areopagan-,NaN,Yeah I wouldnt want to deal with someone like ...,NaN,1515531740,t5_32jqy,t3_72l671,t1_dsfnzvi,1.0,0,0,dsfo2zk,JordanPeterson,NaN,14,14,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3103203,yrelav_dnomyar,NaN,What are your qualities and traits preferred i...,NaN,1471556597,t5_2qowo,t3_4ycvdt,t3_4ycvdt,1.0,0,0,d6n7gwr,intj,1.0,915,896,en
3103204,yrelav_dnomyar,NaN,"Thanks for your input, I too enjoy that the T ...",NaN,1471984713,t5_2qowo,t3_4z35f6,t1_d6tjjmy,2.0,0,0,d6tr1ka,intj,2.0,62,61,en
3103205,yrelav_dnomyar,NaN,WHYYYYYYY,NaN,1515442412,t5_3db06,t3_7p0ihe,t1_dsdluzd,4.0,0,0,dsdqfai,GH5,NaN,1,1,NaN
3103206,yrelav_dnomyar,NaN,"Yes, of course I do! As long as you are super ...",NaN,1522258616,t5_2tm8b,t3_868uag,t1_dw5bdck,2.0,0,0,dwfh3ss,weddingvideography,NaN,27,27,en
3103207,yrelav_dnomyar,NaN,Nailed it.,NaN,1471707411,t5_2qowo,t3_4y4ntn,t1_d6kz4yi,1.0,0,0,d6pgjpp,intj,1.0,2,2,en

In [20]:
smalldata = data.sample(n=1000, random_state=32)
smalldata.to_csv(r"/Users/sophiasylvester/ma_py/pandora_bigfive1000.csv", index=False)
smalldata.head()

,author,author_flair_text,body,downs,created_utc,subreddit_id,link_id,parent_id,score,controversiality,gilded,id,subreddit,ups,word_count,word_count_quoteless,lang
504179,Sabata11792,NaN,Not seeing any break or signal lights and no p...,NaN,1534890968,t5_3fqup,t3_995l9s,t1_e4lbrls,1.0,0,0,e4lkg2l,ATBGE,NaN,19,19,en
2229587,Swarels,INTP,"Multiverses, matrix theory, consciousness. Scr...",NaN,1499749893,t5_2qhvl,t3_6mjw62,t1_dk26jre,7.0,0,0,dk26vpo,INTP,NaN,51,46,en
1182135,pearlz176,Manchester United,Hope you've enjoyed the ride :D,NaN,1485613795,t5_2qi58,t3_5qnd1v,t1_dd0mdqg,2.0,0,0,dd0nxif,soccer,NaN,6,6,en
1272580,rainbowhotpocket,Colts,"Idk, in the AFC if i recall correctly since 20...",NaN,1466965660,t5_2qmg3,t3_4pypuh,t1_d4oulvo,11.0,0,0,d4our0i,nfl,11.0,62,61,en
768556,amathyx,http://myanimelist.net/profile/amathy,22 hours later and the music is still going[co...,NaN,1495851189,t5_2qh22,t3_6ddiow,t3_6ddiow,6.0,0,0,di3inz7,anime,NaN,32,29,en